# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BooksReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_text', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.CharField(max_length=1000)),
                ('author_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksReviewApp.Book')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='review_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksReviewApp.Review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
