# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksReviewApp', '0002_bookrequest'),
        ('BooksReviewApp', '0002_auto_20180113_1047'),
    ]

    operations = [
    ]
